drop table if exists member CASCADE;
create table member
(
id bigint generated by default as identity,
name varchar(255),
content varchar(255),
primary key (id)
);

create table people
(
id varchar(255),
ps varchar(255),
bookmark int(10) default null is null,
primary key (id)
);